name: Setup and Lint

on:
  push:
    branches: [ main ]
    paths-ignore: [ '*.md' ]
  pull_request:
    branches: [ '**' ]
  merge_group:
    branches: [ '**' ]

jobs:
  setup-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install yarn
        run: |
          yarn set version 3.x
          yarn install

      - name: Run linter
        run: yarn eslint --max-warnings=0 .
