name: Setup and Test

on:
  pull_request:
    branches: [ '**' ]
  merge_group:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install yarn
        run: |
          yarn set version 3.x
          yarn install

      - name: Run tests
        run: CI=true yarn test
