name: Setup and Test

on:
  push:
    branches: [ main ]
    paths-ignore: [ '*.md' ]
  pull_request:
    branches: [ '**' ]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install yarn
        run: |
          brew install yarn
          yarn set version 3.x
          yarn install

      - name: Run tests
        run: CI=true yarn test

      - name: Run linter
        run: yarn eslint --max-warnings=0

  dispatch-tag:
    needs: [ setup-and-test ]
    runs-on: ubuntu-latest

    if: success() && github.ref == 'refs/heads/main'

    steps:
      - name: Fire off tag action
        uses: broadinstitute/workflow-dispatch@v1
        with:
          workflow: Tag
          token: ${{ secrets.BROADBOT_TOKEN }}
